# frozen_string_literal: true

require_relative "knowledge_sdk"
require_relative "knowledge_graph/version"
require_relative "knowledge_graph/errors"
require_relative "knowledge_graph/intent"
require_relative "knowledge_graph/intents"
require_relative "knowledge_graph/result"
require_relative "knowledge_graph/hooks/hook_bus"
require_relative "knowledge_graph/executor/dispatcher"
require_relative "knowledge_graph/executor/transaction"
require_relative "knowledge_graph/executor/executor"
require_relative "knowledge_graph/audit/receipt_store"
require_relative "knowledge_graph/audit/audit_log"
require_relative "knowledge_graph/storage/markdown_document"
require_relative "knowledge_graph/storage/yaml_writer"
require_relative "knowledge_graph/storage/schema_registry"
require_relative "knowledge_graph/storage/repository"
require_relative "knowledge_graph/storage/id_generator"
require_relative "knowledge_graph/validation/external_validator"
require_relative "knowledge_graph/entities/entity_manager"
require_relative "knowledge_graph/graph/relationship_registry"
require_relative "knowledge_graph/graph/relationship_manager"
require_relative "knowledge_graph/identity/identity_resolver"
require_relative "knowledge_graph/identity/identity_manager"
require_relative "knowledge_graph/graph_reader"
require_relative "knowledge_graph/engine"
require_relative "knowledge_graph/cli/intent_factory"
require_relative "knowledge_extraction"
require_relative "knowledge_intelligence"
require_relative "knowledge_planning"
require_relative "agent_platform"
require_relative "knowledge_orchestration"
require_relative "knowledge_activity"
require_relative "structured_dataset"
require_relative "knowledge_analysis"
require_relative "knowledge_graph/chat"
require_relative "knowledge_graph/cli/chat_cli"
require_relative "knowledge_graph/cli/cli"

module KnowledgeGraph
end
