# frozen_string_literal: true

require "digest"

module KnowledgeAnalysis
  # Persists a review-only recommendation envelope in the existing Proposal
  # Store. It intentionally contains no executable Intent; adopting a concrete
  # action requires a later, separately approved Intent proposal.
  class RecommendationProposalBuilder
    PIPELINE_VERSION = "knowledge-analysis-recommendation-v1".freeze

    def initialize(vault_root:, event_bus: nil, clock: nil)
      @vault_root = vault_root
      @event_bus = event_bus
      @clock = clock || -> { Time.now }
      @store = KnowledgeExtraction::ProposalStore.new(vault_root: vault_root, clock: @clock)
    end

    def create(question:, recommendations:, analysis_digest:, as_of:)
      selected = Array(recommendations)
      raise RecommendationError, "no recommendations are available" if selected.empty?

      source_id = KnowledgeExtraction::Support.stable_id("source", analysis_digest, question)
      proposal_id = KnowledgeExtraction::Support.stable_id(
        "proposal", source_id, selected.map { |item| item.fetch("recommendation_id") }.sort
      )
      captured_at = normalize_time(as_of)
      evidence = selected.map do |item|
        {
          "evidence_id" => KnowledgeExtraction::Support.stable_id(
            "evidence", proposal_id, item.fetch("recommendation_id")
          ),
          "source_id" => source_id, "start_offset" => 0,
          "end_offset" => question.to_s.length, "excerpt" => question.to_s
        }
      end
      facts = selected.each_with_index.map do |item, index|
        {
          "fact_id" => KnowledgeExtraction::Support.stable_id(
            "fact", proposal_id, item.fetch("recommendation_id")
          ),
          "fact_type" => "analysis_recommendation", "status" => "hypothesis",
          "confidence" => item.fetch("confidence"),
          "subject" => "knowledge-analysis", "predicate" => "possible_recommendation",
          "object" => item.fetch("text"), "evidence" => [evidence.fetch(index)],
          "explanation" => "Derived deterministically from the cited analysis evidence; not an executable action."
        }
      end
      payload = {
        "proposal_id" => proposal_id,
        "source" => {
          "source_id" => source_id, "source_type" => "text", "language" => "und",
          "captured_at" => captured_at, "title" => "Knowledge Analysis recommendations",
          "metadata" => {
            "derived" => true, "analysis_digest" => analysis_digest,
            "recommendation_only" => true, "executable" => false
          },
          "content_hash" => Digest::SHA256.hexdigest(question.to_s)
        },
        "summary" => "#{selected.length} review-only recommendation(s) generated by deterministic analysis.",
        "facts" => facts, "entity_mentions" => [], "resolution_candidates" => [],
        "resolution_decisions" => [], "planned_intents" => [],
        "warnings" => ["Recommendations are non-executable until converted into a separate exact Intent proposal."],
        "conflicts" => [], "required_approvals" => {
          "total" => 0, "blocked" => 0, "by_risk" => { "low" => 0, "medium" => 0, "high" => 0 }
        },
        "rejected_items" => [],
        "model_metadata" => {
          "provider" => "none", "deterministic" => true,
          "recommendations" => selected, "executable" => false
        },
        "prompt_version" => "none", "pipeline_version" => PIPELINE_VERSION,
        "created_at" => captured_at, "status" => "awaiting_approval",
        "ingestion_state" => "new", "metrics" => { "recommendation_count" => selected.length }
      }
      KnowledgeExtraction::ProposalValidator.new.validate!(payload)
      @store.save(payload)
      publish(proposal_id, selected, analysis_digest)
      payload
    rescue KnowledgeExtraction::Error => error
      raise RecommendationError, error.message
    end

    private

    def publish(proposal_id, recommendations, analysis_digest)
      return unless @event_bus

      @event_bus.publish(
        type: "RecommendationGenerated", source: "knowledge-analysis",
        payload: {
          "proposal_id" => proposal_id, "analysis_digest" => analysis_digest,
          "recommendation_ids" => recommendations.map { |item| item.fetch("recommendation_id") },
          "executable" => false
        },
        correlation_id: proposal_id
      )
    rescue KnowledgeOrchestration::Error
      nil
    end

    def normalize_time(value)
      return value.iso8601 if value.respond_to?(:iso8601)

      Time.iso8601(value.to_s).iso8601
    rescue ArgumentError
      @clock.call.iso8601
    end
  end
end
